-- MySQL Script generated by MySQL Workbench
-- Wed Apr 15 18:01:21 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FinancieraBonos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `FinancieraBonos` ;

-- -----------------------------------------------------
-- Schema FinancieraBonos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FinancieraBonos` DEFAULT CHARACTER SET utf8 ;
USE `FinancieraBonos` ;

-- -----------------------------------------------------
-- Table `FinancieraBonos`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FinancieraBonos`.`roles` ;

CREATE TABLE IF NOT EXISTS `FinancieraBonos`.`roles` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_rol`),
  UNIQUE INDEX `id_rol_UNIQUE` (`id_rol` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinancieraBonos`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FinancieraBonos`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `FinancieraBonos`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `id_rol` INT NOT NULL,
  `usuario` VARCHAR(45) NULL,
  `contrasena` VARCHAR(45) NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`id_usuario` ASC) VISIBLE,
  INDEX `id_rol_idx` (`id_rol` ASC) VISIBLE,
  CONSTRAINT `id_rol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `FinancieraBonos`.`roles` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinancieraBonos`.`bonos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FinancieraBonos`.`bonos` ;

CREATE TABLE IF NOT EXISTS `FinancieraBonos`.`bonos` (
  `id_bono` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `flavor` VARCHAR(45) NULL,
  `ticker_symbol` VARCHAR(45) NULL,
  `ticker` VARCHAR(45) NULL,
  `currency` VARCHAR(45) NULL,
  `issue_date` DATE NULL,
  `original_issue_date` VARCHAR(45) NULL,
  `first_coupon_date` DATE NULL,
  `coupon` VARCHAR(45) NULL,
  `maturity_date` DATE NULL,
  `auction_date` DATE NULL,
  `isin` VARCHAR(45) NULL,
  `total_issue_size` DOUBLE NULL,
  PRIMARY KEY (`id_bono`),
  INDEX `id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `FinancieraBonos`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `FinancieraBonos`.`roles`
-- -----------------------------------------------------
START TRANSACTION;
USE `FinancieraBonos`;
INSERT INTO `FinancieraBonos`.`roles` (`id_rol`, `nombre`) VALUES (1, 'Financiero');
INSERT INTO `FinancieraBonos`.`roles` (`id_rol`, `nombre`) VALUES (2, 'Financiero administrador');

COMMIT;

